local util = require("decipher.util")

describe("util", function()
    describe("escape_newlines", function()
        it("escapes newlines", function()
            assert.are.same(util.escape_newlines(""), "")
            assert.are.same(util.escape_newlines("no newlines"), "no newlines")
            assert.are.same(util.escape_newlines("two\nnewlines\n"), "two\\nnewlines\\n")
        end)
    end)
end)
